### PR TITLE
multi host settings panel

### PR DESCRIPTION
**Pull request by florianeck**

### CODE REVIEW

**Comment by florianeck** [comment]
@konne its ready for testing

**Comment by florianeck** [comment]
should fix issues #1 and #2

**Comment by konne** [comment]
@florianeck 
the user will be registered, but the multihost settings are not set: LOG error

`Started` POST "/account/register" for 127.0.0.1 at 2017-01-09 05:53:35 +0100
Processing by AccountController#register as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "user"=>{"login"=>"konne_X", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "firstname"=>"X", "lastname"=>"XQlikAudit", "mail"=>"X@X.name", "language"=>"en"}, "pref"=>{"hide_mail"=>"1"}, "commit"=>"OK"}
  Current user: anonymous
WARNING: Can't mass-assign protected attributes for EasyUserWorkingTimeCalendar: type
        plugins/easyproject/easy_plugins/easy_extensions/app/models/easy_user_time_calendar.rb:86:in `assign_to_user'
        plugins/easyproject/easy_plugins/easy_extensions/lib/easy_patch/redmine/models/user_patch.rb:522:in `create_easy_user_working_time_calendar_from_default'
        app/controllers/account_controller.rb:301:in `register_by_email_activation'
        app/controllers/account_controller.rb:147:in `register'
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  Rendered mailer/register.text.erb within layouts/mailer (0.5ms)
  Rendered mailer/register.html.erb within layouts/mailer (0.4ms)
  Rendered plugins/easyproject/easy_plugins/easy_extensions/app/views/mailer/_easy_styles_common.css (0.3ms)
  Rendered plugins/easyproject/easy_plugins/easy_extensions/app/views/mailer/_easy_non_inline.css (0.3ms)
  Rendered plugins/easyproject/easy_plugins/easy_extensions/app/views/mailer/_easy_styles_outlook.css (0.2ms)
Redirected to http://www.x.com/login
Completed 500 Internal Server Error in 646ms (ActiveRecord: 16.6ms)

NoMethodError (undefined method `<<' for #<Group:0x0000000c91e860>):
  plugins/redmine_multi_hosts/lib/multi_hosts/register_with_hostname.rb:26:in `set_user_multihost_id'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by florianeck** [comment]
@konne i'll check that... seems like the default group cant be found or sth. like that

**Comment by florianeck** [comment]
@konne should b fixed by last commit

**Comment by konne** [comment]
working fine

**Pull request merged**
